---
# GitHub Linguist settings for the repository
#
# This file is used to override GitHub's language detection algorithms for this repository.
# See: https://github.com/github/linguist#overrides

# Prevent certain files from being identified as Shell
override:
  exclude:
    - '**/*.sh'

# Correctly identify the main project languages
project_type: 'nextjs'
primary_language: 'typescript'
frameworks:
  - 'nextjs'
  - 'react'
